version: '3.5'
services:
  daily_dad_jokes:
    image: jcartwright/daily_dad_jokes
    container_name: daily_dad_jokes
    env_file: .env.docker
    depends_on:
      - daily_dad_jokes_db
    ports:
      - "4000:4000"

  daily_dad_jokes_db:
    image: postgres:10-alpine
    container_name: daily_dad_jokes_db
    environment:
      POSTGRES_DB: "daily_dad_jokes_prod"
      POSTGRES_PASSWORD: "postgres"
