apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: daily_dad_jokes_tls
spec:
  secretName: daily_dad_jokes_club
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: dailydadjokes.club
  dnsNames:
    - dailydadjokes.club
    - www.dailydadjokes.club
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - dailydadjokes.club
          - www.dailydadjokes.club
