apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: jcartwright/daily_dad_jokes:latest
          ports:
            - containerPort: 4000
          env:
            - name: APP_HOST
              value: dailydadjokes.club
            - name: HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MESSAGEBIRD_HOST
              value: rest.messagebird.com
            - name: MESSAGEBIRD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: messagebirdapikey
                  key: MESSAGEBIRD_API_KEY
            - name: PORT
              value: "4000"
            - name: POSTGRES_HOST
              value: postgres-cluster-ip-service
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: daily_dad_jokes_prod
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_POOL_SIZE
              value: "20"
            - name: POSTGRES_USER
              value: postgres
            - name: RAPID_API_DAD_JOKES_HOST
              value: dad-jokes.p.rapidapi.com
            - name: RAPID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: rapidapikey
                  key: RAPID_API_KEY
            - name: RELEASE_COOKIE
              value: rimshot
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: secretkeybase
                  key: SECRET_KEY_BASE
            - name: SERVICE_NAME
              value: dailydadjokes.default.svc.cluster.local
